spring:
  application:
    name: booklending

  datasource:
    jdbcUrl: jdbc:postgresql://localhost:5432/lendingbookapp
    username: postgres
    password: P@ssw0rd
    driverClassName: org.postgresql.Driver
    hikari:
        minimumIdle: 5
        maximumPoolSize: 20
        idleTimeout: 600000        # 10 minutes
        connectionTimeout: 30000   # 30 seconds
        maxLifetime: 1800000       # 30 minutes
        poolName: LendingbookAppPool
  jpa:
    hibernate:
      # Automatically manage the schema (validate, update, create, create-drop)
      ddl-auto: update
      # Show generated SQL in the console
      show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      # Further performance tuning for statement caching
      hibernate.hikari.cachePrepStmts: true
      hibernate.hikari.prepStmtCacheSize: 250
      hibernate.hikari.prepStmtCacheSqlLimit: 2048     