spring:
  application:
    name: booklending

  datasource:
    jdbcUrl: jdbc:postgresql://localhost:5432/lendingbookapp
    username: postgres
    password: P@ssw0rd
    driverClassName: org.postgresql.Driver
    hikari:
          # Connection Pool tuning parameters
          minimum-idle: 5
          maximum-pool-size: 20
          idle-timeout: 600000        # 10 minutes
          connection-timeout: 30000   # 30 seconds
          max-lifetime: 1800000       # 30 minutes
          pool-name: LendingbookAppPool
          # Optional: Add validation queries or leak detection
          # connection-test-query: "SELECT 1"
          # leak-detection-threshold: 2000 # Detect connections held for > 2 seconds

    jpa:
       hibernate:
       # Explicitly tell Hibernate it's PostgreSQL
       dialect: org.hibernate.dialect.PostgreSQLDialect
       